service: wetter-api

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1

functions:
  getTemp:
    handler: handler.getTemp
    events:
       - http:
          path: wetter
          method: get
          request:
            parameters:
              querystrings:
                url: true